PackageName: "PartiallySeparableNLPModels"
PackageOwner: "JuliaSmoothOptimizers"
PackageUUID: "7f79d04d-aed5-44bf-a878-92b5ccf934e0"
_src_path: "https://github.com/JuliaSmoothOptimizers/JSOBestieTemplate.jl"
_commit: "7bcc7d0a2905be7ca9d1dd6519e8df59ae89605c"
AddBreakage: true
AddBenchmark: false
AddBenchmarkCI: true
AddCirrusCI: true
